export const UK_LOCAL_AUTHORITIES = [
  "Barking and Dagenham",
  "Barnet",
  "Barnsley",
  "Bath and North East Somerset",
  "Bedford",
  "Bexley",
  "Birmingham",
  "Blackburn with Darwen",
  "Blackpool",
  "Bolton",
  "Bournemouth, Christchurch and Poole",
  "Bracknell Forest",
  "Bradford",
  "Brent",
  "Brighton and Hove",
  "Bristol",
  "Bromley",
  "Buckinghamshire",
  "Bury",
  "Calderdale",
  "Cambridgeshire",
  "Camden",
  "Central Bedfordshire",
  "Cheshire East",
  "Cheshire West and Chester",
  "City of London",
  "Cornwall",
  "Coventry",
  "Croydon",
  "Cumbria",
  "Darlington",
  "Derby",
  "Derbyshire",
  "Devon",
  "Doncaster",
  "Dorset",
  "Dudley",
  "Durham",
  "Ealing",
  "East Riding of Yorkshire",
  "East Sussex",
  "Enfield",
  "Essex",
  "Gateshead",
  "Gloucestershire",
  "Greenwich",
  "Hackney",
  "Halton",
  "Hammersmith and Fulham",
  "Hampshire",
  "Haringey",
  "Harrow",
  "Hartlepool",
  "Havering",
  "Herefordshire",
  "Hertfordshire",
  "Hillingdon",
  "Hounslow",
  "Isle of Wight",
  "Islington",
  "Kensington and Chelsea",
  "Kent",
  "Kingston upon Hull",
  "Kingston upon Thames",
  "Kirklees",
  "Knowsley",
  "Lambeth",
  "Lancashire",
  "Leeds",
  "Leicester",
  "Leicestershire",
  "Lewisham",
  "Lincolnshire",
  "Liverpool",
  "Luton",
  "Manchester",
  "Medway",
  "Merton",
  "Middlesbrough",
  "Milton Keynes",
  "Newcastle upon Tyne",
  "Newham",
  "Norfolk",
  "North East Lincolnshire",
  "North Lincolnshire",
  "North Somerset",
  "North Tyneside",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottingham",
  "Nottinghamshire",
  "Oldham",
  "Oxfordshire",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Reading",
  "Redbridge",
  "Redcar and Cleveland",
  "Richmond upon Thames",
  "Rochdale",
  "Rotherham",
  "Rutland",
  "Salford",
  "Sandwell",
  "Sefton",
  "Sheffield",
  "Shropshire",
  "Slough",
  "Solihull",
  "Somerset",
  "South Gloucestershire",
  "South Tyneside",
  "Southampton",
  "Southend-on-Sea",
  "Southwark",
  "St. Helens",
  "Staffordshire",
  "Stockport",
  "Stockton-on-Tees",
  "Stoke-on-Trent",
  "Suffolk",
  "Sunderland",
  "Surrey",
  "Sutton",
  "Swindon",
  "Tameside",
  "Telford and Wrekin",
  "Thurrock",
  "Torbay",
  "Tower Hamlets",
  "Trafford",
  "Wakefield",
  "Walsall",
  "Waltham Forest",
  "Wandsworth",
  "Warrington",
  "Warwickshire",
  "West Berkshire",
  "West Sussex",
  "Westminster",
  "Wigan",
  "Wiltshire",
  "Windsor and Maidenhead",
  "Wirral",
  "Wokingham",
  "Wolverhampton",
  "Worcestershire",
  "York",
  // Scotland
  "Aberdeen City",
  "Aberdeenshire",
  "Angus",
  "Argyll and Bute",
  "City of Edinburgh",
  "Clackmannanshire",
  "Dumfries and Galloway",
  "Dundee City",
  "East Ayrshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "Falkirk",
  "Fife",
  "Glasgow City",
  "Highland",
  "Inverclyde",
  "Midlothian",
  "Moray",
  "Na h-Eileanan Siar",
  "North Ayrshire",
  "North Lanarkshire",
  "Orkney Islands",
  "Perth and Kinross",
  "Renfrewshire",
  "Scottish Borders",
  "Shetland Islands",
  "South Ayrshire",
  "South Lanarkshire",
  "Stirling",
  "West Dunbartonshire",
  "West Lothian",
  // Wales
  "Blaenau Gwent",
  "Bridgend",
  "Caerphilly",
  "Cardiff",
  "Carmarthenshire",
  "Ceredigion",
  "Conwy",
  "Denbighshire",
  "Flintshire",
  "Gwynedd",
  "Isle of Anglesey",
  "Merthyr Tydfil",
  "Monmouthshire",
  "Neath Port Talbot",
  "Newport",
  "Pembrokeshire",
  "Powys",
  "Rhondda Cynon Taf",
  "Swansea",
  "Torfaen",
  "Vale of Glamorgan",
  "Wrexham",
  // Northern Ireland
  "Antrim and Newtownabbey",
  "Ards and North Down",
  "Armagh City, Banbridge and Craigavon",
  "Belfast",
  "Causeway Coast and Glens",
  "Derry City and Strabane",
  "Fermanagh and Omagh",
  "Lisburn and Castlereagh",
  "Mid and East Antrim",
  "Mid Ulster",
  "Newry, Mourne and Down",
].sort();
