// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnslbftwceqremqsfylk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuc2xiZnR3Y2VxcmVtcXNmeWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MTI2NDcsImV4cCI6MjA3OTI4ODY0N30.mvuOOlnSo7xA_GOuQ_kP9pG8VwUBzQ9QSe3yuJvvXOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});